name: Release

on:
  push:
    branches:
      - '**'        
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install Native AOT dependencies
        run: sudo apt-get update && sudo apt-get install -y clang zlib1g-dev

      #  Publish Linux (Native AOT)
      - name: Publish Linux
        run: |
          dotnet publish ./SamFirm/SamFirm.csproj -c Release -r linux-x64 \
          -p:PublishAot=true \
          -p:StripSymbols=true \
          -o ./dist/linux

      #  Publish macOS (Native AOT)
      - name: Publish macOS
        run: |
          dotnet publish ./SamFirm/SamFirm.csproj -c Release -r osx-x64 \
          -p:PublishAot=true \
          -p:StripSymbols=true \
          -o ./dist/macos

      #  Publish Windows 
      - name: Publish Windows
        run: |
          dotnet publish ./SamFirm/SamFirm.csproj -c Release -r win-x64 \
          -p:PublishAot=true \
          -p:StripSymbols=true \
          -o ./dist/windows


      - name: Prepare Artifacts
        run: |
          mv ./dist/linux/SamFirm ./SamFirm-linux-x64
          mv ./dist/macos/SamFirm ./SamFirm-macos-x64
          mv ./dist/windows/SamFirm.exe ./SamFirm-win-x64.exe


      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SamFirm-binaries
          path: |
            SamFirm-linux-x64
            SamFirm-macos-x64
            SamFirm-win-x64.exe
